version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:2.484
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
      - /home/r3v4n/.ssh/:/var/jenkins_home/.ssh/:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jintea_net

networks:
  jintea_net:
    external: true
